<p>My name is Wesley Barron, and I have played drums for roughly 25 years. Music and playing musicical
instruments has been an interest to me for most of my life. I have been in about 4 or 5 local bands in the
Columbus, GA and Atlanta, GA area, with genres ranging from alternative and punk to metal. After a lot of partying
I decided it was best to seperate myself from the bar scene.</p>
<p>Currently I am on the rotation to play drums and bass at my church. I am also a part of the sound and media team.
Electronic drum triggers was something I was introduced to while playing in metal bands, alot of drummers would trigger
the kick drum in order to produce a <em>"metal"</em> kick sound. I have always been interested in electronics so I began
building triggers. After many failures and some success I decided to covert an accoustic drum set to electronic years
later. Using electronic drums enables more control over the house sound as well as the stage volume, which
was exactly what we needed for our church. I created this web page to give anyone who has an interest in
converting an accoustic drum set to electric some tips and feedback of my success and failures.</p>
<br />
<img src="/content/images/drum1.jpg" alt="drum1 pic" width="650" height="300">
