<p>At last! Let's get started building your hybrid electric drum kit.</p>
<h3>Step 1:</h3>
<p>Find a donor drum kit. You will need a basic acoustic drum kit to get started. Remove all drum heads
from donor kit.<br><br>
<img src="/content/images/basic acoustic drum kit.jpg"></p>
<h3>Step 2:</h3>
<p>Order and install piezo tranducers into drum heads. You will need TRS or TRRS 1/4 inch female jacks at this
time as well. You will need to use a board and metal brakets to center peizo in the drum. After you attach wooden
mounting brace you will adhere piezo to the center of the board using double sided tape or hot glue. You will need
a piece of foam at this time as well. Attach the foam to the top side of the piezo with double sided tape.Finally,
find a good location for the jack and drill a hole in the side of the drum, install and make solder connections.<br><br>
<img src="/content/images/diy-drum-trigger.jpg"><br>
<a href="https://youtu.be/Byq9zh9g7aM" alt="diy trigger video" target="_blank">Click here for a video tutorial.</a></p>
<h3>Step 3:</h3>
<p>Install mesh heads, drum module, and trs or trrs cables and you are ready to rock!<br><br>
<img src="/content/images/drum module.jpg">
<img src="/content/images/mesh-heads.jpg">
<img src="/content/images/trrs-cables.jpg">
</p>
<h4>Schematics you may need</h4>
<p>
<img src="/content/images/piezo transducer science.jpg">
<img src="/content/images/trs or trrs jack 2.jpg">
</p>
<p><a href="http://drummagazine.com/how-to-build-your-own-electronic-kit/" alt="hybrid drum kit pic." target="_blank">Click here for more information.</a></p>