<p>At last! Let's get started building your hybrid electric drum kit.</p>
<h3>Step 1:</h3>
<p>Find a donor drum kit. You will need a basic acoustic drum kit to get started.<br><br>
<img src="content/images/basic acoustic drum kit.jpg</p>
<p><a href="http://drummagazine.com/how-to-build-your-own-electronic-kit/" alt="hybrid drum kit pic." target="_blank">Click here to view this hybrid electric drum kit.</a></p>