<p>This website was created to give you a general overview on what a hybrid electric drumset is and basic steps
and tools needed to make your own. A hybrid electric drum kit is basically an acoustic set of drums with mesh
drum heads, piezo tranducer triggers, and a drum module. Some advantages of electric drum kits include:</p><br>
<ul>
    <li>low stage volume</li>
    <li>low practice volume</li>
    <li>direct input into soundboard</li>
    <li>ability to change drum sounds with the press of a button</li>
    <li>easy recording</li>
    <li>happy sound technician</li>
</ul><br>

<p>Thank you for checking out this page and hope you enjoy and learn a little bit about hybrid electric drum kits.</p>